package fallow:midden;

interface krenel {
	record point {
		x: s32,
		y: s32
	}

	resource actor {
		get-position: func() -> point;
		set-position: func(pos: point);
	}

	spawn: func(kind: string, pos: point) -> actor;
}

world fortalice {
	import krenel;
	import wasi:logging/logging@0.1.0;
	export on-update: func(dt: f32);
}